//------------------------------------------------------------------------------
// <auto-generated>
//      This file is auto-generated!
//      DO NOT MODIFY!
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Diagnostics.CodeAnalysis;

namespace Xilium.CefGlue.Interop
{
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "93.1.11+g9e254fa+chromium-93.0.4577.63";
        public const int CEF_VERSION_MAJOR = 93;
        public const int CEF_COMMIT_NUMBER = 2419;
        public const string CEF_COMMIT_HASH = "9e254face2ebf76ce3ce493933cc8957c3f46f51";
        
        public const int CHROME_VERSION_MAJOR = 93;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 4577;
        public const int CHROME_VERSION_PATCH = 63;
        
        public const string CEF_API_HASH_UNIVERSAL = "5625e3ce80d2bbf5b5a39f8655d96c215f7685ee";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "c20e4ffc24e6267b61774f49237d0f30a581f370";
        public const string CEF_API_HASH_PLATFORM_MACOS = "65731bc654ec6e1dbd48d6ff2336c4c8573f7d35";
        public const string CEF_API_HASH_PLATFORM_LINUX = "4e35b9cc9735c63ac9f16fbbb49a4b8e2307f23a";
    }
}
