//------------------------------------------------------------------------------
// <auto-generated>
//      This file is auto-generated!
//      DO NOT MODIFY!
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Diagnostics.CodeAnalysis;

namespace Xilium.CefGlue.Interop
{
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "95.7.18+g0d6005e+chromium-95.0.4638.69";
        public const int CEF_VERSION_MAJOR = 95;
        public const int CEF_COMMIT_NUMBER = 2460;
        public const string CEF_COMMIT_HASH = "0d6005e731a64d870868b98c5cba6ca96c42ca3b";
        
        public const int CHROME_VERSION_MAJOR = 95;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 4638;
        public const int CHROME_VERSION_PATCH = 69;
        
        public const string CEF_API_HASH_UNIVERSAL = "21ac25aebdb49a8e8088c6fbee802b04fd07b501";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "1d81ccb5ba2f6d658abde2faeb490c8f7f6a60fe";
        public const string CEF_API_HASH_PLATFORM_MACOS = "d6bd1ab64a160962ee0306625da5dd2a0cae8b31";
        public const string CEF_API_HASH_PLATFORM_LINUX = "0b5227787444955a548b7544b2cdcda95a354506";
    }
}
