//------------------------------------------------------------------------------
// <auto-generated>
//      This file is auto-generated!
//      DO NOT MODIFY!
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Diagnostics.CodeAnalysis;

namespace Xilium.CefGlue.Interop
{
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "100.0.22+g4a1240d+chromium-100.0.4896.88";
        public const int CEF_VERSION_MAJOR = 100;
        public const int CEF_COMMIT_NUMBER = 2542;
        public const string CEF_COMMIT_HASH = "4a1240db4988ca33e948e7c0d4215bbd6bc70150";
        
        public const int CHROME_VERSION_MAJOR = 100;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 4896;
        public const int CHROME_VERSION_PATCH = 88;
        
        public const string CEF_API_HASH_UNIVERSAL = "c32d3ae315c5991d1bd81c412635d95a3fd353f8";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "cb1d823e15caa7e7b6074e3e612d111145b374d1";
        public const string CEF_API_HASH_PLATFORM_MACOS = "7e3a768a3b73a514763ce9902afb85775ca8c83d";
        public const string CEF_API_HASH_PLATFORM_LINUX = "bc9260335c9493beb100645dbccd587e62925b9e";
    }
}
